crkn-rcdr/Access-Platform

- Databases/dipstaging.md
Filled in descriptions of some of the existing fields.  If we want to use https://json-schema.org/ at this stage, I have much more reading to do.
> Create dipstaging document

- Databases/design-docs/collection/design/access/views/items.js
- Databases/schemas/collection.json
Allows for easier item list management in current API calls, as well as some long-term planning.
> Migrates item lists to lists of objects

- Databases/canvas/schema.json
> Adds update for a service to check Cantaloupe for image dimension information

- .gitignore
- .vscode/settings.json
- accessor/package.json
- lapin/env.ts
- lapin/index.ts
- lapin/package.json
- lapin/routes/index.ts
- lapin/routes/slug.ts
- lapin/routes/validate.ts
- lapin/run.ts
- lapin/tsconfig.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
> lapin: reincarnated

- README.md
- package.json
- packages/accessor/package.json
- packages/data/package.json
- services/couchdb/package.json
It isn't pretty but it might just work.
> Unified dev script for running everything all at once

- services/admin/src/actions/toggle.ts
- services/admin/src/app.css
- services/admin/src/components/canvases/CanvasThumbnailList.svelte
- services/admin/src/components/canvasmanifests/CanvasSelector.svelte
- services/admin/src/components/canvasmanifests/ContentEditor.svelte
- services/admin/src/components/shared/DynamicDragAndDropList.svelte
- services/admin/src/components/shared/Switch.svelte
- services/admin/src/components/shared/SwitchCase.svelte
- services/admin/src/lib/types.ts
I'm not sure if I should base this off of master or off of the branch this has been created from but I'm just working on the add canvas to manifest here.
> Adding a canvas to a CanvasManifest

- packages/data/src/dmd/Task.ts
- packages/data/src/dmd/index.ts
- packages/data/src/index.ts
- packages/data/src/util/ProcessUpdate.ts
- packages/data/src/util/index.ts
- services/couchdb/dmdtask/design/access/updates/new.js
- services/couchdb/dmdtask/design/access/updates/update.js
- services/couchdb/dmdtask/design/access/views/splitQueue.js
- services/couchdb/dmdtask/design/access/views/splitStatus.js
- services/couchdb/dmdtask/design/access/views/storeQueue.js
- services/couchdb/dmdtask/design/access/views/storeStatus.js
Ported over from #55 into the new system.
There's a lot that needs doing in the design documents but that can be folded into #113.
> DMDTask schema and ddoc functions.

- .dockerignore
- .env.dev
- .env.docker
- .env.prod
- .env.secret.example
- README.md
- docker-compose.yaml
- docs/node_pnpm.md
- packages/couch-utils/README.md
- packages/data/README.md
- packages/env/README.md
- packages/env/src/index.ts
- packages/lapin-router/README.md
- services/couchdb/README.md
- services/couchdb/kivikrc.example.json
- services/haproxy/.gitignore
- services/haproxy/README.md
- services/haproxy/haproxy.cfg
- services/lapin/README.md
- services/proof-of-concept/README.md
Everything about how to run things should be current.
I also moved some environment variable configuration around but nothing should have changed.
> Documentation update

- .env.dev
- .env.prod
- README.md
- docker-compose.yaml
- packages/env/src/index.ts
- packages/lapin-router/package.json
- packages/lapin-router/src/context.ts
- packages/lapin-router/src/context/noid.ts
- pnpm-lock.yaml
- services/admin/src/hooks.ts
- services/couchdb/kivikrc.example.json
- services/haproxy/haproxy.cfg
> Adds noid service; changes DNS aliases back to IP addresses

- packages/couch-utils/src/handlers/access.spec.ts
- packages/couch-utils/src/handlers/access.ts
- packages/lapin-router/src/routes/accessObject.ts
- packages/lapin-router/src/routes/slug.ts
- services/couchdb/access/design/access/updates/editObject.js
- services/couchdb/access/design/access/updates/publish.js
- services/couchdb/access/design/access/updates/removeMember.js
- services/couchdb/access/design/access/updates/unassignSlug.js
- services/couchdb/access/design/access/updates/unpublish.js
- services/couchdb/access/design/metadatabus/updates/forceUpdate.js
- services/couchdb/prelude.js
> Unassigning slugs back-end

- packages/env/README.md
The README file for environment variable setting was out of date.
> env README update

- services/admin/src/lib/components/collections/CollectionMembersAddition.svelte
Nothing fancy yet but a working basic feature. Fancy stuff with validations are to follow.
> Resolving the error with adding members during demo

- services/couchdb/canvas/design/access/views/copycanvasfiles.js
- services/couchdb/canvas/design/access/views/copycanvasimage.js
- services/couchdb/canvas/design/access/views/ocrtype.js
* Copying PDF and image files, not only images.
* A view on OCR type, which will be part of decision to re-OCR the txtmap canvases.
> Some changes to views for Canvases.

- services/admin/src/lib/components/canvases/CanvasThumbnailList.svelte
- services/admin/src/lib/components/manifests/ManifestAddCanvasMenu.svelte
- services/admin/src/lib/components/shared/DropdownMenu.svelte
- services/admin/src/lib/components/shared/SideMenuContainer.svelte
- services/admin/src/lib/components/shared/SideMenuPageList.svelte
- services/admin/src/lib/components/shared/SideMenuPageListButton.svelte
- services/admin/src/lib/components/shared/Toolbar.svelte
- services/admin/static/style.css
> Admin app improvements based on initial feedback

- services/admin/src/lib/components/access-objects/EditorActions.svelte
- services/admin/src/lib/components/collections/CollectionContentEditor.svelte
- services/admin/src/lib/components/dmd/DmdSuccessItemsTable.svelte
- services/admin/src/lib/components/dmd/DmdSuccessView.svelte
- services/admin/src/lib/components/dmd/DmdWaitingView.svelte
- services/admin/src/lib/components/shared/PrefetchLoader.svelte
- services/admin/src/routes/dmd/[taskId]/index.svelte
- services/admin/src/routes/object/[prefix]/[noid].svelte
> Fixes for admin app issues/enhancements

- services/admin/src/lib/components/canvases/CanvasThumbnailList.svelte
- services/admin/src/lib/components/collections/CollectionContentEditor.svelte
- services/admin/src/lib/components/shared/DynamicDragAndDropListItem.svelte
- services/admin/src/lib/components/shared/VirtualList.svelte
Consolidates common code from the member list and the canvas list
> Virtual scrolling component with optional drag and drop added

- packages/couch-utils/src/DatabaseHandler.ts
- packages/lapin-router/src/router.ts
- packages/lapin-router/src/routes/accessObject.ts
- packages/lapin-router/src/routes/collection.ts
- packages/lapin-router/src/routes/dipstaging.ts
- packages/lapin-router/src/routes/dmdTask.ts
- packages/lapin-router/src/routes/manifest.ts
- packages/lapin-router/src/routes/wipmeta.ts
> Cast caught errors explicitly

- packages/lapin-router/src/routes/collection.ts
- services/admin/src/lib/components/collections/CollectionContentEditor.svelte
- services/admin/src/lib/components/collections/CollectionMembersAddition.svelte
The Slug and the Label for Collection members are displayed, The drag and drop works for this. 
My assumptions the logic of the code will change when we work specifically on Pagination part of members
> Members context display

- packages/data/src/access/Pdf.spec.ts
- packages/data/src/access/Pdf.ts
- services/couchdb/access/design/tree/views/pdf.js
Some discussion in https://github.com/crkn-rcdr/Access-Platform/issues/407#issuecomment-998848171 and https://github.com/crkn-rcdr/Access-Platform/issues/384#issuecomment-998933405
> Cleaning up type="pdf" access documents.

- services/couchdb/dipstaging/design/access/updates/updateOCR.js
- services/couchdb/dipstaging/design/access/updates/updateSmelt.js
https://github.com/crkn-rcdr/Access-Platform/issues/368
Also a good time to set up replacement update functions for Smelter as well.
> Adding update functions required for Importing OCR from legacy preservation.

- services/admin/src/routes/smelter/[view]/__layout.svelte
> Fix for off by one error in importer

- packages/lapin-router/src/routes/dmdTask.ts
- packages/lapin-router/src/util/dmdTask.ts
- services/admin/src/lib/components/canvases/CanvasThumbnailList.svelte
- services/admin/src/lib/components/dmd/DmdNewTaskForm.svelte
- services/admin/src/lib/components/dmd/DmdWaitingView.svelte
- services/admin/src/lib/components/dmd/success/DmdSuccessView.svelte
- services/admin/src/lib/components/shared/VirtualList.svelte
- services/admin/src/lib/stores/dmdTasksStore.ts
- services/admin/src/routes/dmd/[taskId]/index.svelte
- services/admin/static/style.css
We were able to determine a list of error strings that would be helpful for the users. I'll be going through the app for the DMD task stuff and adding in or editing those errors into the admin app code and into the dmd task specific code in lapin (which will be moved out eventually)
> Adding new error messages to the metadata updater

- Help.md
- packages/data/src/access/util/ObjectList.ts
- packages/lapin-router/src/routes/collection.ts
- services/admin/src/lib/components/access-objects/Editor.svelte
- services/admin/src/lib/components/access-objects/EditorActions.svelte
- services/admin/src/lib/components/access-objects/EditorForm.svelte
- services/admin/src/lib/components/access-objects/ResolveMany.svelte
- services/admin/src/lib/components/access-objects/TypeAhead.svelte
- services/admin/src/lib/components/canvases/CanvasThumbnailList.svelte
- services/admin/src/lib/components/collections/CollectionContentEditor.svelte
- services/admin/src/lib/components/collections/CollectionMembersAddition.svelte
- services/admin/src/lib/components/dipstaging/DipstagingLegacyPackageTable.svelte
- services/admin/src/lib/components/dipstaging/DipstagingLookup.svelte
- services/admin/src/lib/components/dipstaging/DipstagingLookupTable.svelte
- services/admin/src/lib/components/dmd/DmdWaitingView.svelte
- services/admin/src/lib/components/dmd/success/DmdSuccessItemPreview.svelte
- services/admin/src/lib/components/manifests/ManifestAddCanvasMenu.svelte
- services/admin/src/lib/components/manifests/ManifestContentEditor.svelte
- services/admin/src/routes/__layout.svelte
- services/admin/src/routes/object/edit/[prefix]/[noid].svelte
- services/admin/src/routes/smelter/__layout.svelte
- services/admin/src/routes/smelter/slug/index.svelte
The importer tool's errors are documented thank to Divya but the editor is straightforward so I will not do a table for that portion of the website. 
The help md file was cleaned up and now points to main.
Members and canvas changes are confirmed in the front end.
Bug fix for collection addition added as well
> Cleaning up the help.md file, making sure error message are readable, and collection add member bugfix

- packages/data/src/import/LegacyPackage.ts
- packages/lapin-router/src/routes/dipstaging.ts
- pnpm-lock.yaml
- services/admin/package.json
- services/admin/src/lib/components/dipstaging/DipstagingLegacyPackageTable.svelte
- services/admin/src/lib/components/dipstaging/DipstagingLookup.svelte
- services/admin/src/lib/components/dipstaging/DipstagingLookupTable.svelte
- services/admin/src/lib/components/dipstaging/DipstatingImportStatus.svelte
- services/admin/src/routes/smelter/find/index.svelte
> Allow people to clear the last import status for a package in the importer 

- packages/couch-utils/src/handlers/access.ts
- services/admin/src/lib/components/access-objects/EditorActions.svelte
Published manifest with metadata: 
https://access-dev.canadiana.ca/object/edit/69429/m06w9668dv41
Unpublished manifest with metadata: 
https://access-dev.canadiana.ca/object/edit/69429/m0m61bk1c53w
Unpublished manifest without metadata: 
https://access-dev.canadiana.ca/object/edit/69429/g0jw86h4cx52
Published collection with metadata:
https://access-dev.canadiana.ca/object/edit/69429/s01j9765bk7h 
Unpublished collection with metadata: 
(Just unpublished above)
Unpublished collection without metadata: 
https://access-dev.canadiana.ca/object/edit/69429/g0pn8x921p72
> Can't publish objects without dmdType set (publish button gets disabled)

- Help.md
- services/couchdb/access/design/access/updates/processList.js
> Fixing a bug in the add members - prepend option (they were getting added in reverse) + adding the link to the workflows guide to the help menu

- docker-compose.yaml
https://github.com/crkn-rcdr/Access-Platform/issues/525
> Test the latest haproxy docker image.

- Dockerfile
- packages/couch-utils/src/DatabaseHandler.ts
- pnpm-lock.yaml
- services/admin/package.json
- services/admin/src/app.html
- services/admin/src/hooks.ts
- services/admin/src/lib/components/access-objects/Editor.svelte
- services/admin/src/lib/components/access-objects/EditorActions.svelte
- services/admin/src/lib/components/collections/CollectionMemberListManager.svelte
- services/admin/src/lib/components/dmd/DmdItemsTable.svelte
- services/admin/src/lib/utils/validation.ts
- services/admin/src/routes/__layout.svelte
- services/admin/src/routes/index.svelte
- services/admin/src/routes/object/edit/[prefix]/[noid].svelte
- services/couchdb/index.js
My dev env was failing to build so I set the svelte version to the last stable release explicitly 
Then I fixed the issue for the module error on new tab load
Then I fixed the issue of not being able to publish pdfs
> Admin bug fixes - module versions, open in a new tab module error (lodash), and pdf publishing

- packages/data/src/dmd/types.ts
- services/admin/src/lib/components/dmd/DmdNewTaskForm.svelte
This is the web interface side of https://github.com/crkn-rcdr/Access-Platform/issues/573
> Load Metadata: MARC - ID in 856

- packages/data/src/access/Manifest.ts
- services/couchdb/access/design/metadatabus/updates/cancelOCRPDF.js
- services/couchdb/access/design/metadatabus/updates/requestOCRPDF.js
- services/couchdb/access/design/metadatabus/updates/updateOCRPDF.js
- services/couchdb/access/design/metadatabus/views/OCRPDFQueue.js
- services/couchdb/access/design/metadatabus/views/OCRPDFStatus.js
- services/couchdb/access/design/tree/views/pdf.js
https://github.com/crkn-rcdr/Access-Platform/issues/90
> CouchDB design for simple service to generate multi-page PDFs.

- services/couchdb/canvas/design/access/views/browsesource.js
- services/couchdb/canvas/design/stats/views/masterext.js
- services/couchdb/canvas/design/stats/views/ocrtype.js
https://github.com/crkn-rcdr/Access-Platform/issues/585
>  View to enable Browsing Image Canvases

- services/couchdb/access/design/metadatabus/views/OCRPDFStatus.js
https://github.com/crkn-rcdr/Access-Platform/issues/590
Kivik deploy to production may need to be coordinated with other UI changes that access this view.
> Add in 'type' to divide status
