.gitignore, docker-compose.yml, haproxy/README.md, haproxy/generate_test_cert.sh, haproxy/haproxy.cfg.example
Yes, I moved stuff around in it for no good reason.
This uses IP addresses instead of DNS, so that switching what your local DNS points to on the regular doesn't require restarting everything.
Access platform repos are going to have default configs that expect this is running.
=> Default HAProxy config

haproxy/haproxy.cfg.example
The logging doesn't otherwise indicate http/https, or what host was being requested.
An extra '/' was being added to the URLs being redirected.
=> Some minor updates for logging and redirects.

Databases/schemas/collection.json, Databases/schemas/manifest.json
This is one possible resolution for #23
=> dmdType should be optional for collection and manifest documents.

services/lapin/package.json
Closes #220.
Unfortunately will need to be updated every time one of lapin's repo dependencies changes its dependencies. I contemplating actually having this be set up in the root repo's package.json but that seems messier.
=> lapin dev `watch`: watch packages' `dist` directories and not, well, everything

pnpm-lock.yaml, services/admin/package.json, services/admin/src/lib/validation.ts
I noticed with the other method that when I added the same canvases from: https://access-dev.canadiana.ca/object/69429/m02n4zg6h671 to itself (selected the first couple canvases) that the isequal from fast deep equals returned true, which is wrong. So I switched to using:
https://www.npmjs.com/package/lodash.isequal
I saw somewhere on github that we will make our own implementation, I'll switch to that once it's done.
=> Replace isequal from fast-deep-equals with lodash's single module for .isequal for canvas comparison

services/admin/src/lib/components/access-objects/Editor.svelte, services/admin/src/lib/components/shared/SideMenuPageListButton.svelte, services/admin/static/style.css
Maybe font colour can be used to indicate the active page? Any time I set the background to something too contrasting to the rest of the page my eyes go directly to the side nav instead of the editor fields.
On hover we can do some more fancy stuff, like lightening the background a fair bit.
=> Sidenav increase contrast between active and inactive tabs

packages/lapin-router/src/routes/dmdTask.ts, services/admin/src/lib/components/dmd/DmdNewTaskForm.svelte, services/admin/src/lib/components/dmd/DmdSplitFailureViewer.svelte, services/admin/src/lib/components/dmd/DmdSplitSuccessStoreForm.svelte, services/admin/src/lib/components/dmd/DmdSplitWaitingViewer.svelte, services/admin/src/lib/components/dmd/DmdTaskTimeInfoTable.svelte, services/admin/src/lib/components/shared/Loading.svelte, services/admin/src/lib/components/shared/NotificationBar.svelte, services/admin/src/routes/__layout.svelte, services/admin/src/routes/dmd/[taskId]/index.svelte, services/admin/src/routes/dmd/new.svelte, services/admin/static/style.css
=> Dmd Task: Step 1-3 Front-end

packages/data/src/dmd/index.ts, packages/data/src/index.ts, packages/lapin-router/src/router.ts, packages/lapin-router/src/routes/dmdTask.ts, services/admin/src/lib/components/dmd/DmdNewTaskForm.svelte, services/admin/src/lib/components/dmd/DmdSplitFailureViewer.svelte, services/admin/src/lib/components/dmd/DmdSplitWaitingViewer.svelte, services/admin/src/lib/components/dmd/DmdTaskTimeInfoTable.svelte, services/admin/src/routes/dmd/[taskId]/index.svelte
Input:
```ts
type NewInput = {
user: User;
mdType: "csvissueinfo" | "csvdc" | "marc490" | "marcoocihm" | "marcooe";
file: string;
};
```
Creates a new `dmdtask` document, through a couch-utils method, with an auto-generated uuid, the dmdType, and the file inserted as an attachment. Theoretically, since it's already base64-encoded, the `_attachments` object can be built in the initial request. Will have to research this a little bit. Decoding the string and then uploading it the standard way can work as an alternative.
Grabs the dmd task by id from the database
=> DMD task: Step 1-3 Lapin routes

services/admin/src/lib/components/dmd/DmdItemLookup.svelte
The response format for slug.resolveMany was changed, which broke the implementation of the lookup component for dmd task metadata updates.
=> Fixing the front-end code for the DMD task items lookup to work with new response format

services/couchdb/access/fixtures/69429_m0bz6154gh7n.json, services/couchdb/canvas/design/access/views/copycanvasimage.js, services/couchdb/canvas/fixtures/69429_c02r3nx9kj8p.json, services/couchdb/canvas/fixtures/69429_c06d5pb4d58z.json, services/couchdb/canvas/fixtures/69429_c0dz0311c62f.json, services/couchdb/canvas/fixtures/69429_c0jq0ss90z39.json, services/couchdb/canvas/fixtures/69429_c0pg1hk6nq31.json, services/couchdb/canvas/fixtures/69429_c0t727c49g60.json, services/couchdb/canvas/fixtures/69429_c0z02z51z77x.json
See: https://github.com/crkn-rcdr/Access-Platform/issues/137
=> Test data for Cantaloupe handling the `extension` field for canvases.

services/admin/src/lib/components/access-objects/InfoEditor.svelte, services/admin/src/lib/components/canvases/CanvasThumbnailList.svelte, services/admin/src/lib/components/collections/CollectionContentEditor.svelte, services/admin/src/lib/components/manifests/ManifestAddCanvasMenu.svelte, services/admin/src/lib/components/manifests/ManifestContentEditor.svelte, services/admin/src/lib/components/shared/SideMenuBody.svelte, services/admin/src/lib/components/shared/SideMenuContainer.svelte, services/admin/src/lib/components/shared/VirtualList.svelte, services/admin/static/style.css
You may need to run pnpm install, there's a new virtual scrolling library added
The behaviour is added to the general info tab, for collections only.
The only options are: unordered, multi-part.
If the collection is unordered, the user can only delete items, not re-order them in the manage members tab.
=> Adding Collection Behaviour to the Editor

packages/data/src/import/LegacyPackage.ts, services/couchdb/canvas/design/access/views/cihmsourcepath.js, services/couchdb/canvas/design/access/views/copycanvasfiles.js, services/couchdb/dipstaging/design/access/updates/cancelOCR.js, services/couchdb/dipstaging/design/access/updates/cancelSmelt.js, services/couchdb/dipstaging/design/access/updates/requestOCR.js, services/couchdb/dipstaging/design/access/updates/requestSmelt.js, services/couchdb/dipstaging/design/access/views/ocrQueue.js, services/couchdb/dipstaging/design/access/views/ocrStatus.js, services/couchdb/prelude.js
This is related to https://github.com/crkn-rcdr/Access-Platform/issues/368
* Smelter will look up to see if image canvases already exist using [_view/cihmsource](https://github.com/crkn-rcdr/Access-Platform/blob/main/services/couchdb/canvas/design/access/views/cihmsource.js) , and create the canvases otherwise.
* Re-smelting can't be used to add OCR to images that have already been smelted, so a different process will exist that will find the OCR that matches the image, and attach that to the canvas.
* The UI should allow people the option of processing the OCR.  This can use the same tool as smelting, but should be different button as they may happen at different times.
=> Changes required to support separating of OCR data processing from Smelter.

packages/couch-utils/src/handlers/access.ts, packages/data/src/access/index.ts, packages/data/src/index.ts, services/admin/src/lib/components/access-objects/Editor.svelte, services/admin/src/lib/components/access-objects/InfoEditor.svelte, services/admin/src/routes/object/[prefix]/[noid].svelte, services/admin/static/style.css
Closes #94, with the caveat that this isn't going to display the entire ancestry tree all at once, for probable performance nightmare reasons. Users can click links to view the collections this object is a member of, and can also remove the object's membership in a collection.
I'll also fix a bug in which components don't seem to reset properly when traversing between objects. This is a known Svelte issue (feature?) that we figured out how to work around in Sapindale.
=> Membership display / editing

services/admin/src/lib/components/access-objects/EditorActions.svelte, services/admin/src/lib/components/manifests/ManifestAddCanvasMenu.svelte
Hey @DivyaKrishnan26 I had to edit the add canvas menu to support long labels for the selected manifest. I also replaced the select all, deselect all icons because they were not being found on prod.
=> Layout fixes for the add canvas menu on prod

services/admin/src/lib/components/dipstaging/DipstagingLegacyPackageTable.svelte, services/admin/src/lib/components/dipstaging/DipstagingLookup.svelte, services/admin/src/lib/components/dipstaging/DipstagingLookupTable.svelte, services/admin/src/routes/smelter/[view]/__layout.svelte
Closes #430 
To test please go to packages with recent activity -> find a manifest with an unavailable slug -> enter a slug that is available -> select it -> press import -> go to queue and see that the slug you entered is marked as available. 
I can make this queue view have a non-editable slug after fix is confirmed too, since it really shouldn't be an input there.
=> Importer bug-fix

Help.md, Helper.md, services/admin/src/routes/__layout.svelte
https://github.com/crkn-rcdr/Access-Platform/issues/402
For the issue linked above I have added a link to Glossary and the Editor actions show and tell documentation, Let me know if thats fine or do we want to change the link to something else.
=> Adding links to helper icons

packages/lapin-router/src/routes/accessObject.ts
Now no matter what type an object is:
If it has the file.extension, it will delete the file
If it has the ocrPdf.extension, it will delete the ocr
And if it has the dmdType property, it will delete the metadata file.
Let me know if you spot anything else!
=> Simplify the deletion checks

services/couchdb/copresentation2/design/access/views/manifest_noid.js, services/couchdb/cosearch2/design/access/views/manifest_noid.js, services/couchdb/internalmeta2/design/tdr/updates/basic.js
This will be used to remve pages when a manifest is removed, rather than making assumptions about the structure of a slug (there may be more than one `.`)
See https://github.com/crkn-rcdr/Access-Platform/issues/400
=> Indexing `manifest_noid` rather than `pkey`.  

packages/couch-utils/src/DatabaseHandler.ts, packages/couch-utils/src/handlers/access.ts, packages/lapin-router/package.json, packages/lapin-router/src/routes/collection.ts, packages/lapin-router/src/routes/manifest.ts, pnpm-lock.yaml, services/admin/src/lib/components/access-objects/EditorActions.svelte
I tested yesterday with the news collection, renaming it to newspapers. As well with my own small collection. Everything forked as expected. I tested the generalisation with my small collection. I'm going to run it again to reset the news collection too.
=> Force updates for collection members when important fields change, and force update parent collections when manifests updated

services/admin/src/lib/components/access-objects/EditorForm.svelte, services/admin/src/lib/components/collections/CollectionMembersAddition.svelte, services/couchdb/access/design/access/updates/publish.js, services/couchdb/prelude.js
Two fixes, one for creating a new collection bug introduced when the updateInternalmeta status feature was added to the editor, the other checks for dmdType before updating updateInternalmeta to trigger hammer
=> Adding dmdType check in couchdb updateObject design doc  (forceUpdate & editObject) + fixed a bug with the create new collection/manifest button

packages/couch-utils/src/DatabaseHandler.ts, packages/couch-utils/src/handlers/access.ts, packages/couch-utils/src/handlers/dipstaging.ts, packages/lapin-router/src/routes/collection.ts, packages/lapin-router/src/routes/wipmeta.ts, services/admin/src/lib/components/access-objects/EditorActions.svelte, services/admin/src/lib/components/access-objects/PrefixSlugSearchbox.svelte, services/admin/src/lib/components/collections/CollectionContentEditor.svelte, services/admin/src/lib/components/collections/CollectionMembersAddition.svelte, services/admin/src/lib/components/dipstaging/DipstagingLookup.svelte, services/admin/src/lib/components/manifests/ManifestContentEditor.svelte, services/admin/src/lib/utils/validation.ts
As Beth was testing she ran into a few problems (https://github.com/crkn-rcdr/Access-Platform/issues/464)
The requests to couch are chunked (for now, we can look into the couch configs to increase the timeout later) to handle very large arrays of slugs. (See changes to files in couch-utils) A check for duplicates was also added to the request for adding members, since Beth noticed she had duplicate members added.
There are some more checks done in the slug search and the input was moved to a re-usable component to remove code duplication between the importer and member addition. See /components/access-objects/PrefixSlugSearchbox.svelte and the handleSlugsChange method for the checks done.
I quickly added the publish status of collection members as I was touching up the member search with …
=> Support for large queries on the importer and add member pages. Show collection member publish status in listing.

services/couchdb/dipstaging/design/access/updates/requestSmelt.js
A trivial fix....
I believe that whenever a new Smelt is requested that any past OCR processing of that package should be cleared.  If the Smelt is successful, then the OCR processing will get re-run some time in the future.
=> When launching new smelt, clear past OCR data processing.

packages/lapin-router/src/routes/accessObject.ts, packages/lapin-router/src/routes/collection.ts, services/admin/src/lib/components/collections/CollectionMemberListManager.svelte
Adding checks for multipart before updating all members except for removals - those only trigger updates to the members being removed.
I wasn't sure if it would be better to add a check to a collection being multi-part in the bulkForceUpdateAllMembers method. Or, keep it out of the method to make it more flexible.
=> Extra checks for multi-part before updating members

docker-compose.yaml, services/admin/src/lib/components/access-objects/EditorForm.svelte, services/admin/src/lib/components/access-objects/Resolver.svelte, services/admin/src/lib/components/access-objects/SlugSearch.svelte, services/admin/src/lib/components/dipstaging/DipstagingLookupTable.svelte, services/admin/src/lib/components/shared/DynamicDragAndDropList.svelte
Please see the following screenshots, and let me know if anything should be changed!
Importer, refresh button allows the same slug to be searched again.
Editor, refresh button allows the same slug to be searched again.
There will be a loading status on search (helpful for slow connections)
I've tested the import process and slug editing process.
=> Importer enhancement & slug set to AIP id on page load

packages/lapin-router/src/routes/collection.ts, services/admin/src/lib/components/access-objects/EditorForm.svelte
Tested all of the add/remove operations all working as expected on my end, triggering updates for only the members that were added or removed for unordered collections, with multi-part functionality remaining the same as it was
=> Update cache for unordered collections - add and remove members routes

services/couchdb/access/design/access/views/noid2slug.js
I have many tools which result in noids, but I want to give lists of slugs to staff.  I had been using the _find interface, but that is extremely slow when looking up a large number of noids.
```
"selector" => {
"_id" => {
'$in' => \@needocr
}
},
```
This creates a lookup which starts at the smallest value of $in and then looks at every database entry until it gets to the largest value in $in.
=> View for quickly looking up the slug

services/couchdb/dipstaging/design/access/updates/requestSmelt.js
If 
* slug='', then delete the (optional) existing slug
* slug=$slug means set the slug
* slug='' means delete the slug, no slug parameter means no change.
https://github.com/crkn-rcdr/Access-Platform/issues/585#issuecomment-1525628156
=> Supporting slug being optional in `dipstaging` records.
